services:

  web:
    build: ./notes
    restart: on-failure
    ports:
      - '8000:8000'
    env_file: ".env"
    depends_on:
      - pg
  

  pg:
    env_file: "./notes/.env"
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"